name: "Check Versions Bumped"
description: "Check if versions are bumped in the PR"
inputs:
  github-token:
    description: "GitHub token"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
