name: "Check Versions Bumped"
description: "Check if versions are bumped in the PR"
inputs:
  token:
    description: "GitHub token"
    required: true
  version-before:
    description: "Version before"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
